Starter TestCafe tests for 311
CityOfBoston/digital pull request #208
Opened 2018-12-12 21:31 UTC by fionaclock

- Adds fake implementations of all services 311 relies on so the server
   can start up without any configuration.
 - API key and Mapbox tweaks for when they’re not configured.
 - Tests for the services page and the search page.

Also:
 - Changes env var names for Open311 endpoint
 - Fixes "javascript:void(0)" syntax errors

2018-12-12 22:05 UTC, jessicamarcus requested changes

2018-12-12 22:05 UTC, jessicamarcus commented on services-js/311/components/request/home/HomePane.tsx
> +                    <a href="javascript:void(0)" onClick={this.startChat}>
Could these be changed to buttons? It would be more semantic and accessible.

2018-12-12 22:05 UTC, jessicamarcus commented on services-js/311/components/search/RecentRequests.tsx
>                    <a
Here too...

2018-12-12 22:05 UTC, jessicamarcus commented on services-js/311/server/server.ts
> +  const dev = !process.env.NODE_ENV || process.env.NODE_ENV === 'development';
👍 Super readable change.

2018-12-12 22:05 UTC, jessicamarcus commented on services-js/311/server/services/Open311.ts
> +  datatype:
❤️ specificity

2018-12-12 22:05 UTC, jessicamarcus commented on services-js/311/server/services/Open311.ts
> +  definitions?: {
❤️ and even moar specificity!

2018-12-12 22:05 UTC, jessicamarcus commented on services-js/311/server/services/PredictionFake.ts
> +    return ['BIRDINFEST', 'CEMTRYMAIN', 'MTRECYDBI'];
![ij1m](https://user-images.githubusercontent.com/5561280/49901738-ff99fd00-fe2f-11e8-97af-c69f3208fbf7.gif)

2018-12-12 22:05 UTC, jessicamarcus commented on services-js/311/server/services/Salesforce.ts
> +/**
Great comment!

2018-12-13 14:29 UTC, fionawhim commented on services-js/311/components/request/home/HomePane.tsx
> +                    <a href="javascript:void(0)" onClick={this.startChat}>
Good idea. Looks like the `lnk` class handles that style.

2018-12-13 14:30 UTC, fionaclock commented on services-js/311/server/services/PredictionFake.ts
> +    return ['BIRDINFEST', 'CEMTRYMAIN', 'MTRECYDBI'];
![da4](https://user-images.githubusercontent.com/260837/49944946-a8d90580-feb9-11e8-9004-48a1b449bf4d.gif)

2018-12-13 14:52 UTC, jessicamarcus approved these changes

2018-12-13 18:44 UTC, merged